### ISSUE TITLE
The result of handwriting classes

### ISSUE THREAD

**Issue by Zackie-D** [AndSonder/HandWritingEraser-Pytorch#3]
Thank you very much for your sharing. I have a question. I have used the model scheme of DeeplabV3plus+ResNet101 and used the data set you provided for training in the main script with default parameters, and the final results are not satisfactory. The prediction of the white background of the document occupies too large a proportion, and the final IOU for the classification result of handwritten handwriting only reaches 0.6+. May I ask if there is any way to optimize this situation for the segmentation task? Looking forward to your reply.
![Snipaste_2023-03-02_10-58-44](https://user-images.githubusercontent.com/74707923/222319682-7ca761c1-d9cc-4f02-8566-f2b2d6a9d928.jpg)

**Comment by AndSonder** [comment]
可以参考一些更复杂的网络结构，https://aistudio.baidu.com/aistudio/projectdetail/3481217?channelType=0&channel=0
